name: magic_sign_mobile
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^2.2.0
  intl: ^0.19.0
  fl_chart: ^0.68.0
  shimmer: ^2.0.0
  cupertino_icons: ^1.0.6
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  sizer: ^2.0.15
  dart_format: ^1.1.17
  get: ^4.6.6
  shared_preferences: ^2.2.2
  video_player: ^2.8.3
  syncfusion_flutter_pdfviewer: ^25.1.35
  flutter_file_view: ^2.2.1
  file_picker: ^8.0.0+1
  syncfusion_flutter_calendar: ^25.2.6+1
  lazy_loading_list: ^1.0.1
  cached_network_image_builder: ^0.3.0
  cached_network_image: ^3.3.1
  sqflite: ^2.3.3+1
  connectivity_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^4.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"
  background_color: "#ffffff"

  
flutter:

  uses-material-design: true
  assets:
    - assets/images/

